version: '3.8'

services:
  db:
    image: ankane/pgvector
    container_name: news_pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_db
    volumes:
      - pg_data:/var/lib/postgresql/pg_data
  
volumes:
  pg_data: